### ISSUE TITLE
Photo of the day stuck at August 21

### ISSUE THREAD

**Issue by lucamp** [msal/muzei-nationalgeographic#3]
Hi,
the photo of the day is no longer updated since August 21 (neon nights). Activating a random photo works but only with photos posted before that date. Have no idea why

Thanks for your app
Luca

**Comment by msal** [comment]
Thanks a lot for the message, @lucamp !

Looks like NG hasn't updated its RSS feed (which the app uses as source) since that date:
http://feeds.nationalgeographic.com/ng/photography/photo-of-the-day/

This happened already once before for some days, until they fixed this server-side issue. However, it seems that this they revamped their entire web presence including an overhauled site and relying on social media like Facebook and Instagram, giving me doubt that they will provide an "old fashioned" RSS feed again.
In that case, I'd have to check if I could parse the site, instead. But what I've seen up to now that looks very hard.

**Comment by lucamp** [comment]
I see what you mean and I found:

[http://www.nationalgeographic.com/photography/photo-of-the-day](http://www.nationalgeographic.com/photography/photo-of-the-day) points always to the latest photo of the day

If I visit that page and open firefox's page info (CTRL+I) there are some interesting fields:

og:image = link that point directly to the picture to download
og:title = photo's title
Photo's full description is only in the page content

Unfortunately I am not able to go far than that as I do not know javascript

Luca

**Comment by msal** [comment]
Yes, it is indeed relatively simple to get the current photo of the day. However, displaying a random one seems much harder. But maybe the current photo is already the main purpose this Muzei plugin is used and I could reduce the functionality to that.

Good thinking, thanks! I will reflect on that.

**Comment by lucamp** [comment]
Sure, the main goal of your program is to have the latest photo of the day.

But if you are wiling to put effort in the random mode maybe there is a 
way to have it working.

NG for muzei saves a single copy of the photo of the day inside a 
folder, as soon as the folder is populated the program picks up a random 
one. The folder must not grow to big, so let it say only the latest 30 
photos remain saved and the other are automatically removed.

According to "National Geographic Terms of Service" this will not 
infringe it:

http://www.nationalgeographic.com/community/terms/ section " 
Intellectual Property Issues" paragraph

Pursuant to the copyright and trademark laws of the United States, /you 
agree/:

 1. That you may only download Content that National Geographic
    designates as offered for download to any single computer a single
    copy of any Content for personal and noncommercial use.

Luca

**Comment by msal** [comment]
Fixed with 319fbe13789aff48945743954b3d4ed00f746fdb

**Comment by lucamp** [comment]
Stiil waiting for the updated version to be released on F-droid, hope it do not take them too much.
Meanwhile, thanks for your efforts.

Luca
